name: "On Push"

on:
  push:
    branches:
      - "*"

env: 
  IS_MERGED: ${{ github.event.pull_request.merged }}
jobs:  
  list-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "list files"
        run: |
          listFiles=$(git diff --name-only HEAD HEAD~1)

          for file in $listFiles
          do 
              echo $file
          done 
