name: "On PR closed"

on:
  pull_request:
    types: [closed]

env: 
  IS_MERGED: ${{ github.event.pull_request.merged }}
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: "Print contexts"
        run: | 
          echo "${{ toJson(github.event.pull_request) }}"
  
  list-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "list files"
        if: ${{ env.IS_MERGED == 'true' }}
        run: |
          listFiles=$(git diff --name-only HEAD HEAD^)

          for file in $listFiles
          do 
              echo $file
          done 
